<a href="https://colab.research.google.com/github/nisha3p/Mars-Rover-20-21/blob/main/TennisBallDetection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
import keras
model=tf.keras.models.load_model('/content/drive/MyDrive/Copy of vgg16_model.h5')

In [ ]:
import tensorflow as tf
import keras
from keras.preprocessing import image
path='/content/drive/MyDrive/Photos'
import numpy as np
import os
c=0
for f in os.listdir(path):
  img_pred = image.load_img(os.path.join(path,f), target_size = (160,160))
  img_pred = image.img_to_array(img_pred)
  img_pred = np.expand_dims(img_pred, axis=0)
  rslt = model.predict(img_pred)
  print (rslt)
  if rslt[0][0]>0.5:
    c+=1
    prediction = "random"
  else:
    prediction = "tennis ball"
  print(prediction)

[[0. 1.]]
tennis ball
[[0. 1.]]
tennis ball
[[0. 1.]]
tennis ball
[[0. 1.]]
tennis ball
[[0. 1.]]
tennis ball
[[0. 1.]]
tennis ball
[[0. 1.]]
tennis ball
[[0. 1.]]
tennis ball
[[0. 1.]]
tennis ball
[[0. 1.]]
tennis ball
[[0. 1.]]
tennis ball
[[0. 1.]]
tennis ball
[[7.913462e-30 1.000000e+00]]
tennis ball
[[0. 1.]]
tennis ball
[[0. 1.]]
tennis ball
[[0. 1.]]
tennis ball
[[0. 1.]]
tennis ball
[[0. 1.]]
tennis ball
[[0. 1.]]
tennis ball
[[0. 1.]]
tennis ball
[[0. 1.]]
tennis ball
