In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
!nvidia-smi

Mon Feb  1 09:24:37 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   57C    P8    10W /  70W |      0MiB / 15079MiB |      0%      Default |
|                               |                      |                 ERR! |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
import tensorflow as tf
tf .__version__

'2.4.1'

In [ ]:
import keras,os
from tensorflow.keras import Sequential
from keras.layers import Conv2D 
from keras.layers import MaxPool2D
from keras.layers import Flatten
from keras.layers import Dense
from keras.preprocessing.image import ImageDataGenerator
import numpy as np

In [ ]:
trdata = ImageDataGenerator()
traindata = trdata.flow_from_directory(directory= '/content/drive/MyDrive/Drishti/Dataset5/train', target_size = (160,160))
tsdata = ImageDataGenerator()
testdata = tsdata.flow_from_directory(directory= '/content/drive/MyDrive/Drishti/Dataset5/test', target_size = (160,160))

Found 3432 images belonging to 2 classes.
Found 858 images belonging to 2 classes.


In [ ]:
VGG = keras.applications.VGG16(input_shape=(160,160,3), include_top = False, weights = 'imagenet')

VGG.trainable = False

model = keras.Sequential([
  VGG,
  keras.layers.Flatten(),
  keras.layers.Dense(units=256,activation="relu"),
  keras.layers.Dense(units=256,activation="relu"),
  keras.layers.Dense(units=2,activation="softmax")
])


58892288/58889256 [==============================] - 0s 0us/step


In [ ]:
model.compile(optimizer='adam',loss=keras.losses.categorical_crossentropy, metrics=['accuracy'])

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
vgg16 (Functional)           (None, 5, 5, 512)         14714688  
_________________________________________________________________
flatten (Flatten)            (None, 12800)             0         
_________________________________________________________________
dense (Dense)                (None, 256)               3277056   
_________________________________________________________________
dense_1 (Dense)              (None, 256)               65792     
_________________________________________________________________
dense_2 (Dense)              (None, 2)                 514       
Total params: 18,058,050
Trainable params: 3,343,362
Non-trainable params: 14,714,688
_________________________________________________________________


In [ ]:
hist = model.fit_generator(steps_per_epoch=100, generator=traindata, validation_data=testdata, validation_steps=10, epochs=5)


/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py:1844: UserWarning: `Model.fit_generator` is deprecated and will be removed in a future version. Please use `Model.fit`, which supports generators.
  warnings.warn('`Model.fit_generator` is deprecated and '


Epoch 1/5
100/100 [==============================] - 393s 4s/step - loss: 0.2680 - accuracy: 0.9811 - val_loss: 0.5979 - val_accuracy: 0.9656
Epoch 2/5
100/100 [==============================] - 134s 1s/step - loss: 0.1670 - accuracy: 0.9880 - val_loss: 0.0758 - val_accuracy: 0.9937
Epoch 3/5
100/100 [==============================] - 74s 746ms/step - loss: 0.0569 - accuracy: 0.9931 - val_loss: 0.5493 - val_accuracy: 0.9625
Epoch 4/5
100/100 [==============================] - 49s 489ms/step - loss: 0.0486 - accuracy: 0.9965 - val_loss: 0.0445 - val_accuracy: 0.9906
Epoch 5/5
100/100 [==============================] - 30s 303ms/step - loss: 0.0161 - accuracy: 0.9978 - val_loss: 0.2386 - val_accuracy: 0.9688


In [ ]:
model.save('/content/drive/MyDrive/vgg16_model.h5')

In [ ]:
import tensorflow as tf
import keras
from keras.preprocessing import image
path='/content/drive/MyDrive/pics'
import numpy as np
import os
c=0
for f in os.listdir(path):
  img_pred = image.load_img(os.path.join(path,f), target_size = (160,160))
  img_pred = image.img_to_array(img_pred)
  img_pred = np.expand_dims(img_pred, axis=0)
  rslt = model.predict(img_pred)
  print (rslt)
  if rslt[0][0]>0.5:
    c+=1
    prediction = "random"
  else:
    prediction = "tennis ball"
  print(prediction)

[[1.0000000e+00 7.2398793e-34]]
random
[[0. 1.]]
tennis ball
[[0. 1.]]
tennis ball
[[8.826234e-19 1.000000e+00]]
tennis ball
[[1.000000e+00 3.879206e-12]]
random
[[0. 1.]]
tennis ball
[[2.7827625e-32 1.0000000e+00]]
tennis ball


In [ ]:
img_pred = image.load_img('/content/drive/MyDrive/pics/img_20210201_002245.jpg', target_size = (160,160))
img_pred = image.img_to_array(img_pred)
img_pred = np.expand_dims(img_pred, axis=0)

result = model.predict(img_pred)
print (result)
if result[0][0] == 1:
  prediction = "random"
else:
  prediction = "ball"

print(prediction)

[[0. 1.]]
ball
